import 'package:flutter/material.dart';

const primaryColor = Color(0xfff05d5e);
const icsearch = "assets/icons/search.png";
const icdustbin = "assets/icons/dustbin.png";
const ichome = "assets/icons/home.png";
const iclist = "assets/icons/list.png";
const icchat = "assets/icons/chat.png";
const icnoti = "assets/icons/notification.png";
const icprofile = "assets/icons/user.png";
const icinvite = "assets/icons/invite.png";
const icbchat = "assets/icons/bubble-chat.png";
const icclub = "assets/icons/community.png";
const icfaq = "assets/icons/faq.png";
const icfeed = "assets/icons/feedback.png";
const ichelp = "assets/icons/help.png";
const icmess = "assets/icons/message.png";
const icset = "assets/icons/setting.png";
const icstats = "assets/icons/statstics.png";
const icterm = "assets/icons/terms.png";
const icabout = "assets/icons/about.png";
